# ./docker-compose.yml

version: '3'

services:
  db:
    build:
      context: ./BD
    volumes:
      - ./volumeDB:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_PORT=3306
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=password
     - PMA_ABSOLUTE_URI=http://192.168.100.172/psdadmin/
     - PMA_ARBITRARY=1
    restart: always
    depends_on: 
     - db
    ports:
     - "8101:80"

volumes:
  volumeDB:

networks:
  default:
    external:
      name: brDown
